version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge